### ISSUE TITLE
Can we discuss more on discord?

### ISSUE THREAD

**Issue by SpeederSpeederSpeder** [zeropse/bitlife-unlocker#2]
Can we discuss more on discord please ?

**Comment by zeropse** [comment]
Sure add me .. my discord id = chornx66

**Comment by zeropse** [comment]
Kindly add me and discuss the details.. I'll close this issue soon. @SpeederSpeederSpeder

**Comment by SpeederSpeederSpeder** [comment]
> Kindly add me and discuss the details.. I'll close this issue soon. @SpeederSpeederSpeder 

Yes, my name in discord is matzkrampitz.
